In [7]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [8]:
df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [9]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [10]:
encoder=OneHotEncoder()

In [12]:
encoded=encoder.fit_transform(df[['color']]).toarray()

In [15]:
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [16]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [17]:
encoder.transform([['blue']]).toarray()

c:\Users\ravin\anaconda3\envs\ml_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [18]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [19]:
#label encoder

In [21]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [23]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [24]:
lbl_encoder.fit_transform(df[['color']])

c:\Users\ravin\anaconda3\envs\ml_env\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [25]:
lbl_encoder.transform([['red']])

c:\Users\ravin\anaconda3\envs\ml_env\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [26]:
lbl_encoder.transform([['blue']])

c:\Users\ravin\anaconda3\envs\ml_env\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [27]:
lbl_encoder.transform([['green']])

c:\Users\ravin\anaconda3\envs\ml_env\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

In [28]:
# order encoding

In [29]:
from sklearn.preprocessing import OrdinalEncoder

In [30]:
df=pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [31]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [32]:
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [33]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [34]:
encoder.transform([['small']])

c:\Users\ravin\anaconda3\envs\ml_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])